---
- name: create the SSL directory
  file:
    path: /etc/sensu/ssl
    owner: "{{ sensu_server_user }}"
    group: "{{ sensu_server_group }}"
    mode: 0750
    state: directory

- name: copy the SSL certificate & key
  copy:
    src: files/sensu_{{ item }}.pem
    dest: /etc/sensu/ssl/{{ item }}.pem
    owner: "{{ sensu_server_user }}"
    group: "{{ sensu_server_group }}"
    mode: 0640
    backup: yes
  with_items:
    - client_cert
    - client_key
